app = 'servern8n'
primary_region = 'mad'

[build]
  dockerfile = "./Dockerfile"

[env]
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  N8N_PROTOCOL = "http"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_LOG_LEVEL = "debug"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.http]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
